# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1183, 696)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.main_hrz = QtGui.QHBoxLayout()
        self.main_hrz.setObjectName(_fromUtf8("main_hrz"))
        self.left_pane = QtGui.QVBoxLayout()
        self.left_pane.setObjectName(_fromUtf8("left_pane"))
        self.radio_pane = QtGui.QVBoxLayout()
        self.radio_pane.setObjectName(_fromUtf8("radio_pane"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.radio_pane.addWidget(self.label_2)
        self.radio0 = QtGui.QHBoxLayout()
        self.radio0.setObjectName(_fromUtf8("radio0"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.radio0.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.radio0.addItem(spacerItem)
        self.led_radio0_plugged = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_radio0_plugged.sizePolicy().hasHeightForWidth())
        self.led_radio0_plugged.setSizePolicy(sizePolicy)
        self.led_radio0_plugged.setState(KLed.Off)
        self.led_radio0_plugged.setShape(KLed.Rectangular)
        self.led_radio0_plugged.setColor(QtGui.QColor(0, 255, 0))
        self.led_radio0_plugged.setDarkFactor(400)
        self.led_radio0_plugged.setObjectName(_fromUtf8("led_radio0_plugged"))
        self.radio0.addWidget(self.led_radio0_plugged)
        self.label_37 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.radio0.addWidget(self.label_37)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.radio0.addItem(spacerItem1)
        self.led_radio0_paired = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_radio0_paired.sizePolicy().hasHeightForWidth())
        self.led_radio0_paired.setSizePolicy(sizePolicy)
        self.led_radio0_paired.setState(KLed.Off)
        self.led_radio0_paired.setShape(KLed.Rectangular)
        self.led_radio0_paired.setColor(QtGui.QColor(0, 255, 0))
        self.led_radio0_paired.setDarkFactor(400)
        self.led_radio0_paired.setObjectName(_fromUtf8("led_radio0_paired"))
        self.radio0.addWidget(self.led_radio0_paired)
        self.label_32 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.radio0.addWidget(self.label_32)
        self.radio_pane.addLayout(self.radio0)
        self.progress_radio0 = QtGui.QProgressBar(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.progress_radio0.setFont(font)
        self.progress_radio0.setMinimum(-96)
        self.progress_radio0.setMaximum(27)
        self.progress_radio0.setProperty("value", -96)
        self.progress_radio0.setInvertedAppearance(False)
        self.progress_radio0.setObjectName(_fromUtf8("progress_radio0"))
        self.radio_pane.addWidget(self.progress_radio0)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.radio_pane.addItem(spacerItem2)
        self.radio1 = QtGui.QHBoxLayout()
        self.radio1.setObjectName(_fromUtf8("radio1"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.radio1.addWidget(self.label_3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.radio1.addItem(spacerItem3)
        self.led_radio1_plugged = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_radio1_plugged.sizePolicy().hasHeightForWidth())
        self.led_radio1_plugged.setSizePolicy(sizePolicy)
        self.led_radio1_plugged.setState(KLed.Off)
        self.led_radio1_plugged.setShape(KLed.Rectangular)
        self.led_radio1_plugged.setColor(QtGui.QColor(0, 255, 0))
        self.led_radio1_plugged.setDarkFactor(400)
        self.led_radio1_plugged.setObjectName(_fromUtf8("led_radio1_plugged"))
        self.radio1.addWidget(self.led_radio1_plugged)
        self.label_36 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.radio1.addWidget(self.label_36)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.radio1.addItem(spacerItem4)
        self.led_radio1_paired = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_radio1_paired.sizePolicy().hasHeightForWidth())
        self.led_radio1_paired.setSizePolicy(sizePolicy)
        self.led_radio1_paired.setState(KLed.Off)
        self.led_radio1_paired.setShape(KLed.Rectangular)
        self.led_radio1_paired.setColor(QtGui.QColor(0, 255, 0))
        self.led_radio1_paired.setDarkFactor(400)
        self.led_radio1_paired.setObjectName(_fromUtf8("led_radio1_paired"))
        self.radio1.addWidget(self.led_radio1_paired)
        self.label_33 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.radio1.addWidget(self.label_33)
        self.radio_pane.addLayout(self.radio1)
        self.progress_radio1 = QtGui.QProgressBar(self.centralwidget)
        self.progress_radio1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_radio1.sizePolicy().hasHeightForWidth())
        self.progress_radio1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.progress_radio1.setFont(font)
        self.progress_radio1.setMinimum(-96)
        self.progress_radio1.setMaximum(27)
        self.progress_radio1.setProperty("value", -96)
        self.progress_radio1.setInvertedAppearance(False)
        self.progress_radio1.setObjectName(_fromUtf8("progress_radio1"))
        self.radio_pane.addWidget(self.progress_radio1)
        self.left_pane.addLayout(self.radio_pane)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.left_pane.addWidget(self.line)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.left_pane.addWidget(self.label_4)
        self.cam0 = QtGui.QHBoxLayout()
        self.cam0.setObjectName(_fromUtf8("cam0"))
        self.led_cam0 = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_cam0.sizePolicy().hasHeightForWidth())
        self.led_cam0.setSizePolicy(sizePolicy)
        self.led_cam0.setState(KLed.Off)
        self.led_cam0.setColor(QtGui.QColor(0, 255, 0))
        self.led_cam0.setDarkFactor(400)
        self.led_cam0.setObjectName(_fromUtf8("led_cam0"))
        self.cam0.addWidget(self.led_cam0)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cam0.addWidget(self.label_5)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.cam0.addItem(spacerItem5)
        self.combo_cam0 = QtGui.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(9)
        self.combo_cam0.setFont(font)
        self.combo_cam0.setObjectName(_fromUtf8("combo_cam0"))
        self.combo_cam0.addItem(_fromUtf8(""))
        self.combo_cam0.addItem(_fromUtf8(""))
        self.cam0.addWidget(self.combo_cam0)
        self.tool_cam0_show = QtGui.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/media/icons/eye_inv_icon&16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/media/icons/invisible_revert_icon&16.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tool_cam0_show.setIcon(icon)
        self.tool_cam0_show.setCheckable(True)
        self.tool_cam0_show.setObjectName(_fromUtf8("tool_cam0_show"))
        self.cam0.addWidget(self.tool_cam0_show)
        self.tool_cam0_start = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_cam0_start.sizePolicy().hasHeightForWidth())
        self.tool_cam0_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setBold(True)
        font.setWeight(75)
        self.tool_cam0_start.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/media/icons/connect_icon&16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/media/icons/disconnected_icon&16.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tool_cam0_start.setIcon(icon1)
        self.tool_cam0_start.setCheckable(True)
        self.tool_cam0_start.setChecked(False)
        self.tool_cam0_start.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.tool_cam0_start.setAutoRaise(False)
        self.tool_cam0_start.setObjectName(_fromUtf8("tool_cam0_start"))
        self.cam0.addWidget(self.tool_cam0_start)
        self.left_pane.addLayout(self.cam0)
        self.cam1 = QtGui.QHBoxLayout()
        self.cam1.setObjectName(_fromUtf8("cam1"))
        self.led_cam1 = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_cam1.sizePolicy().hasHeightForWidth())
        self.led_cam1.setSizePolicy(sizePolicy)
        self.led_cam1.setState(KLed.Off)
        self.led_cam1.setColor(QtGui.QColor(0, 255, 0))
        self.led_cam1.setDarkFactor(400)
        self.led_cam1.setObjectName(_fromUtf8("led_cam1"))
        self.cam1.addWidget(self.led_cam1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cam1.addWidget(self.label_6)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.cam1.addItem(spacerItem6)
        self.combo_cam1 = QtGui.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(9)
        self.combo_cam1.setFont(font)
        self.combo_cam1.setObjectName(_fromUtf8("combo_cam1"))
        self.combo_cam1.addItem(_fromUtf8(""))
        self.combo_cam1.addItem(_fromUtf8(""))
        self.cam1.addWidget(self.combo_cam1)
        self.tool_cam1_show = QtGui.QToolButton(self.centralwidget)
        self.tool_cam1_show.setIcon(icon)
        self.tool_cam1_show.setCheckable(True)
        self.tool_cam1_show.setObjectName(_fromUtf8("tool_cam1_show"))
        self.cam1.addWidget(self.tool_cam1_show)
        self.tool_cam1_start = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_cam1_start.sizePolicy().hasHeightForWidth())
        self.tool_cam1_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setBold(True)
        font.setWeight(75)
        self.tool_cam1_start.setFont(font)
        self.tool_cam1_start.setIcon(icon1)
        self.tool_cam1_start.setCheckable(True)
        self.tool_cam1_start.setChecked(False)
        self.tool_cam1_start.setObjectName(_fromUtf8("tool_cam1_start"))
        self.cam1.addWidget(self.tool_cam1_start)
        self.left_pane.addLayout(self.cam1)
        self.cam2 = QtGui.QHBoxLayout()
        self.cam2.setObjectName(_fromUtf8("cam2"))
        self.led_cam2 = KLed(self.centralwidget)
        self.led_cam2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_cam2.sizePolicy().hasHeightForWidth())
        self.led_cam2.setSizePolicy(sizePolicy)
        self.led_cam2.setState(KLed.Off)
        self.led_cam2.setColor(QtGui.QColor(0, 255, 0))
        self.led_cam2.setDarkFactor(400)
        self.led_cam2.setObjectName(_fromUtf8("led_cam2"))
        self.cam2.addWidget(self.led_cam2)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.cam2.addWidget(self.label_7)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.cam2.addItem(spacerItem7)
        self.combo_cam2 = QtGui.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(9)
        self.combo_cam2.setFont(font)
        self.combo_cam2.setObjectName(_fromUtf8("combo_cam2"))
        self.combo_cam2.addItem(_fromUtf8(""))
        self.combo_cam2.addItem(_fromUtf8(""))
        self.cam2.addWidget(self.combo_cam2)
        self.tool_cam2_show = QtGui.QToolButton(self.centralwidget)
        self.tool_cam2_show.setIcon(icon)
        self.tool_cam2_show.setCheckable(True)
        self.tool_cam2_show.setObjectName(_fromUtf8("tool_cam2_show"))
        self.cam2.addWidget(self.tool_cam2_show)
        self.tool_cam2_start = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_cam2_start.sizePolicy().hasHeightForWidth())
        self.tool_cam2_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setBold(True)
        font.setWeight(75)
        self.tool_cam2_start.setFont(font)
        self.tool_cam2_start.setIcon(icon1)
        self.tool_cam2_start.setCheckable(True)
        self.tool_cam2_start.setChecked(False)
        self.tool_cam2_start.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tool_cam2_start.setObjectName(_fromUtf8("tool_cam2_start"))
        self.cam2.addWidget(self.tool_cam2_start)
        self.left_pane.addLayout(self.cam2)
        self.cam3 = QtGui.QHBoxLayout()
        self.cam3.setObjectName(_fromUtf8("cam3"))
        self.led_cam3 = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_cam3.sizePolicy().hasHeightForWidth())
        self.led_cam3.setSizePolicy(sizePolicy)
        self.led_cam3.setState(KLed.Off)
        self.led_cam3.setColor(QtGui.QColor(0, 255, 0))
        self.led_cam3.setDarkFactor(400)
        self.led_cam3.setObjectName(_fromUtf8("led_cam3"))
        self.cam3.addWidget(self.led_cam3)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cam3.addWidget(self.label_8)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.cam3.addItem(spacerItem8)
        self.combo_cam3 = QtGui.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(9)
        self.combo_cam3.setFont(font)
        self.combo_cam3.setObjectName(_fromUtf8("combo_cam3"))
        self.combo_cam3.addItem(_fromUtf8(""))
        self.combo_cam3.addItem(_fromUtf8(""))
        self.cam3.addWidget(self.combo_cam3)
        self.tool_cam3_show = QtGui.QToolButton(self.centralwidget)
        self.tool_cam3_show.setIcon(icon)
        self.tool_cam3_show.setCheckable(True)
        self.tool_cam3_show.setObjectName(_fromUtf8("tool_cam3_show"))
        self.cam3.addWidget(self.tool_cam3_show)
        self.tool_cam3_start = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_cam3_start.sizePolicy().hasHeightForWidth())
        self.tool_cam3_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setBold(True)
        font.setWeight(75)
        self.tool_cam3_start.setFont(font)
        self.tool_cam3_start.setIcon(icon1)
        self.tool_cam3_start.setCheckable(True)
        self.tool_cam3_start.setChecked(False)
        self.tool_cam3_start.setObjectName(_fromUtf8("tool_cam3_start"))
        self.cam3.addWidget(self.tool_cam3_start)
        self.left_pane.addLayout(self.cam3)
        self.cam4 = QtGui.QHBoxLayout()
        self.cam4.setObjectName(_fromUtf8("cam4"))
        self.led_cam4 = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_cam4.sizePolicy().hasHeightForWidth())
        self.led_cam4.setSizePolicy(sizePolicy)
        self.led_cam4.setState(KLed.Off)
        self.led_cam4.setColor(QtGui.QColor(0, 255, 0))
        self.led_cam4.setDarkFactor(400)
        self.led_cam4.setObjectName(_fromUtf8("led_cam4"))
        self.cam4.addWidget(self.led_cam4)
        self.label_20 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.cam4.addWidget(self.label_20)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.cam4.addItem(spacerItem9)
        self.combo_cam4 = QtGui.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(9)
        self.combo_cam4.setFont(font)
        self.combo_cam4.setObjectName(_fromUtf8("combo_cam4"))
        self.combo_cam4.addItem(_fromUtf8(""))
        self.combo_cam4.addItem(_fromUtf8(""))
        self.cam4.addWidget(self.combo_cam4)
        self.tool_cam4_show = QtGui.QToolButton(self.centralwidget)
        self.tool_cam4_show.setIcon(icon)
        self.tool_cam4_show.setCheckable(True)
        self.tool_cam4_show.setObjectName(_fromUtf8("tool_cam4_show"))
        self.cam4.addWidget(self.tool_cam4_show)
        self.tool_cam4_start = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_cam4_start.sizePolicy().hasHeightForWidth())
        self.tool_cam4_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setBold(True)
        font.setWeight(75)
        self.tool_cam4_start.setFont(font)
        self.tool_cam4_start.setIcon(icon1)
        self.tool_cam4_start.setCheckable(True)
        self.tool_cam4_start.setChecked(False)
        self.tool_cam4_start.setObjectName(_fromUtf8("tool_cam4_start"))
        self.cam4.addWidget(self.tool_cam4_start)
        self.left_pane.addLayout(self.cam4)
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.left_pane.addWidget(self.line_9)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_2.addWidget(self.label_14)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.led_xbox = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_xbox.sizePolicy().hasHeightForWidth())
        self.led_xbox.setSizePolicy(sizePolicy)
        self.led_xbox.setState(KLed.Off)
        self.led_xbox.setShape(KLed.Rectangular)
        self.led_xbox.setDarkFactor(400)
        self.led_xbox.setObjectName(_fromUtf8("led_xbox"))
        self.horizontalLayout_7.addWidget(self.led_xbox)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_7.addWidget(self.label_16)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.led_haptic = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_haptic.sizePolicy().hasHeightForWidth())
        self.led_haptic.setSizePolicy(sizePolicy)
        self.led_haptic.setState(KLed.Off)
        self.led_haptic.setShape(KLed.Rectangular)
        self.led_haptic.setDarkFactor(400)
        self.led_haptic.setObjectName(_fromUtf8("led_haptic"))
        self.horizontalLayout_6.addWidget(self.led_haptic)
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_6.addWidget(self.label_19)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.left_pane.addLayout(self.verticalLayout_2)
        self.line_13 = QtGui.QFrame(self.centralwidget)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.left_pane.addWidget(self.line_13)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.left_pane.addItem(spacerItem12)
        self.label_30 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMaximumSize(QtCore.QSize(160, 113))
        self.label_30.setText(_fromUtf8(""))
        self.label_30.setPixmap(QtGui.QPixmap(_fromUtf8(":/media/nova_logo.png")))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.left_pane.addWidget(self.label_30)
        self.main_hrz.addLayout(self.left_pane)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.main_hrz.addWidget(self.line_2)
        self.middle_pane = QtGui.QVBoxLayout()
        self.middle_pane.setObjectName(_fromUtf8("middle_pane"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_28 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet(_fromUtf8(""))
        self.label_28.setTextFormat(QtCore.Qt.AutoText)
        self.label_28.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_8.addWidget(self.label_28)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.label_21 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_8.addWidget(self.label_21)
        self.label_vehicle = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.label_vehicle.setFont(font)
        self.label_vehicle.setObjectName(_fromUtf8("label_vehicle"))
        self.horizontalLayout_8.addWidget(self.label_vehicle)
        self.middle_pane.addLayout(self.horizontalLayout_8)
        self.line_15 = QtGui.QFrame(self.centralwidget)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.middle_pane.addWidget(self.line_15)
        self.stack_mission = QtGui.QStackedWidget(self.centralwidget)
        self.stack_mission.setObjectName(_fromUtf8("stack_mission"))
        self.page_setup = QtGui.QWidget()
        self.page_setup.setObjectName(_fromUtf8("page_setup"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_setup)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_12 = QtGui.QLabel(self.page_setup)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.line_16 = QtGui.QFrame(self.page_setup)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.verticalLayout.addWidget(self.line_16)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.button_sandstorm = QtGui.QPushButton(self.page_setup)
        self.button_sandstorm.setMinimumSize(QtCore.QSize(0, 64))
        self.button_sandstorm.setObjectName(_fromUtf8("button_sandstorm"))
        self.horizontalLayout_2.addWidget(self.button_sandstorm)
        self.button_rover = QtGui.QPushButton(self.page_setup)
        self.button_rover.setMinimumSize(QtCore.QSize(0, 64))
        self.button_rover.setObjectName(_fromUtf8("button_rover"))
        self.horizontalLayout_2.addWidget(self.button_rover)
        self.button_simulator = QtGui.QPushButton(self.page_setup)
        self.button_simulator.setMinimumSize(QtCore.QSize(0, 64))
        self.button_simulator.setAutoDefault(False)
        self.button_simulator.setDefault(False)
        self.button_simulator.setFlat(False)
        self.button_simulator.setObjectName(_fromUtf8("button_simulator"))
        self.horizontalLayout_2.addWidget(self.button_simulator)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        self.stack_mission.addWidget(self.page_setup)
        self.page_ert = QtGui.QWidget()
        self.page_ert.setObjectName(_fromUtf8("page_ert"))
        self.verticalLayout1 = QtGui.QVBoxLayout(self.page_ert)
        self.verticalLayout1.setObjectName(_fromUtf8("verticalLayout1"))
        self.label_122 = QtGui.QLabel(self.page_ert)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_122.setFont(font)
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.verticalLayout1.addWidget(self.label_122)
        self.line_17 = QtGui.QFrame(self.page_ert)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.verticalLayout1.addWidget(self.line_17)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout1.addItem(spacerItem15)
        self.stack_mission.addWidget(self.page_ert)
        self.page_auto = QtGui.QWidget()
        self.page_auto.setObjectName(_fromUtf8("page_auto"))
        self.verticalLayout2 = QtGui.QVBoxLayout(self.page_auto)
        self.verticalLayout2.setObjectName(_fromUtf8("verticalLayout2"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_129 = QtGui.QLabel(self.page_auto)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_129.setFont(font)
        self.label_129.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_129.setObjectName(_fromUtf8("label_129"))
        self.horizontalLayout_21.addWidget(self.label_129)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem16)
        self.label_39 = QtGui.QLabel(self.page_auto)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_21.addWidget(self.label_39)
        self.label_auto_state = QtGui.QLabel(self.page_auto)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_auto_state.setFont(font)
        self.label_auto_state.setObjectName(_fromUtf8("label_auto_state"))
        self.horizontalLayout_21.addWidget(self.label_auto_state)
        self.verticalLayout2.addLayout(self.horizontalLayout_21)
        self.line_20 = QtGui.QFrame(self.page_auto)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.verticalLayout2.addWidget(self.line_20)
        self.label_35 = QtGui.QLabel(self.page_auto)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout2.addWidget(self.label_35)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_22 = QtGui.QLabel(self.page_auto)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_3.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(self.page_auto)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_3.addWidget(self.label_23)
        self.horizontalLayout_24.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.edit_lat = QtGui.QLineEdit(self.page_auto)
        self.edit_lat.setMaxLength(20)
        self.edit_lat.setObjectName(_fromUtf8("edit_lat"))
        self.verticalLayout_4.addWidget(self.edit_lat)
        self.edit_lng = QtGui.QLineEdit(self.page_auto)
        self.edit_lng.setMaxLength(20)
        self.edit_lng.setObjectName(_fromUtf8("edit_lng"))
        self.verticalLayout_4.addWidget(self.edit_lng)
        self.horizontalLayout_24.addLayout(self.verticalLayout_4)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem17)
        self.pushButton = QtGui.QPushButton(self.page_auto)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_24.addWidget(self.pushButton)
        self.verticalLayout2.addLayout(self.horizontalLayout_24)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout2.addItem(spacerItem18)
        self.stack_mission.addWidget(self.page_auto)
        self.page_debug = QtGui.QWidget()
        self.page_debug.setObjectName(_fromUtf8("page_debug"))
        self.verticalLayout3 = QtGui.QVBoxLayout(self.page_debug)
        self.verticalLayout3.setObjectName(_fromUtf8("verticalLayout3"))
        self.label_124 = QtGui.QLabel(self.page_debug)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_124.setFont(font)
        self.label_124.setObjectName(_fromUtf8("label_124"))
        self.verticalLayout3.addWidget(self.label_124)
        self.line_19 = QtGui.QFrame(self.page_debug)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.verticalLayout3.addWidget(self.line_19)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout3.addItem(spacerItem19)
        self.stack_mission.addWidget(self.page_debug)
        self.middle_pane.addWidget(self.stack_mission)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.middle_pane.addWidget(self.line_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8(""))
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem20)
        self.label_38 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout.addWidget(self.label_38)
        self.combo_mission = QtGui.QComboBox(self.centralwidget)
        self.combo_mission.setEnabled(True)
        self.combo_mission.setEditable(False)
        self.combo_mission.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.combo_mission.setObjectName(_fromUtf8("combo_mission"))
        self.combo_mission.addItem(_fromUtf8(""))
        self.combo_mission.addItem(_fromUtf8(""))
        self.combo_mission.addItem(_fromUtf8(""))
        self.combo_mission.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.combo_mission)
        self.middle_pane.addLayout(self.horizontalLayout)
        self.modes = QtGui.QHBoxLayout()
        self.modes.setObjectName(_fromUtf8("modes"))
        self.button_standby = QtGui.QPushButton(self.centralwidget)
        self.button_standby.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.button_standby.setFont(font)
        self.button_standby.setStyleSheet(_fromUtf8(""))
        self.button_standby.setCheckable(False)
        self.button_standby.setObjectName(_fromUtf8("button_standby"))
        self.modes.addWidget(self.button_standby)
        self.button_drive = QtGui.QPushButton(self.centralwidget)
        self.button_drive.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.button_drive.setFont(font)
        self.button_drive.setStyleSheet(_fromUtf8(""))
        self.button_drive.setCheckable(False)
        self.button_drive.setObjectName(_fromUtf8("button_drive"))
        self.modes.addWidget(self.button_drive)
        self.button_arm = QtGui.QPushButton(self.centralwidget)
        self.button_arm.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.button_arm.setFont(font)
        self.button_arm.setStyleSheet(_fromUtf8(""))
        self.button_arm.setCheckable(False)
        self.button_arm.setObjectName(_fromUtf8("button_arm"))
        self.modes.addWidget(self.button_arm)
        self.button_drill = QtGui.QPushButton(self.centralwidget)
        self.button_drill.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.button_drill.setFont(font)
        self.button_drill.setStyleSheet(_fromUtf8(""))
        self.button_drill.setCheckable(False)
        self.button_drill.setObjectName(_fromUtf8("button_drill"))
        self.modes.addWidget(self.button_drill)
        self.button_auto = QtGui.QPushButton(self.centralwidget)
        self.button_auto.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.button_auto.setFont(font)
        self.button_auto.setStyleSheet(_fromUtf8(""))
        self.button_auto.setCheckable(False)
        self.button_auto.setObjectName(_fromUtf8("button_auto"))
        self.modes.addWidget(self.button_auto)
        self.middle_pane.addLayout(self.modes)
        self.main_hrz.addLayout(self.middle_pane)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.main_hrz.addWidget(self.line_4)
        self.right_pane = QtGui.QVBoxLayout()
        self.right_pane.setObjectName(_fromUtf8("right_pane"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem21)
        self.right_pane.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.kled = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kled.sizePolicy().hasHeightForWidth())
        self.kled.setSizePolicy(sizePolicy)
        self.kled.setState(KLed.Off)
        self.kled.setShape(KLed.Rectangular)
        self.kled.setDarkFactor(400)
        self.kled.setObjectName(_fromUtf8("kled"))
        self.horizontalLayout_9.addWidget(self.kled)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_9.addWidget(self.label_11)
        self.label_voltage = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_voltage.setFont(font)
        self.label_voltage.setObjectName(_fromUtf8("label_voltage"))
        self.horizontalLayout_9.addWidget(self.label_voltage)
        self.progress_voltage = QtGui.QProgressBar(self.centralwidget)
        self.progress_voltage.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_voltage.sizePolicy().hasHeightForWidth())
        self.progress_voltage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.progress_voltage.setFont(font)
        self.progress_voltage.setMinimum(230)
        self.progress_voltage.setMaximum(252)
        self.progress_voltage.setProperty("value", 230)
        self.progress_voltage.setTextVisible(False)
        self.progress_voltage.setInvertedAppearance(False)
        self.progress_voltage.setObjectName(_fromUtf8("progress_voltage"))
        self.horizontalLayout_9.addWidget(self.progress_voltage)
        self.right_pane.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_10.addWidget(self.label_13)
        self.label_speed = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_speed.setFont(font)
        self.label_speed.setObjectName(_fromUtf8("label_speed"))
        self.horizontalLayout_10.addWidget(self.label_speed)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem22)
        self.led_relay = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_relay.sizePolicy().hasHeightForWidth())
        self.led_relay.setSizePolicy(sizePolicy)
        self.led_relay.setState(KLed.Off)
        self.led_relay.setShape(KLed.Rectangular)
        self.led_relay.setColor(QtGui.QColor(0, 255, 0))
        self.led_relay.setDarkFactor(400)
        self.led_relay.setObjectName(_fromUtf8("led_relay"))
        self.horizontalLayout_10.addWidget(self.led_relay)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_10.addWidget(self.label_15)
        self.right_pane.addLayout(self.horizontalLayout_10)
        self.line_18 = QtGui.QFrame(self.centralwidget)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.right_pane.addWidget(self.line_18)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_12.addWidget(self.label_17)
        self.label_lat = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_lat.setFont(font)
        self.label_lat.setObjectName(_fromUtf8("label_lat"))
        self.horizontalLayout_12.addWidget(self.label_lat)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem23)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_12.addWidget(self.label_18)
        self.label_lng = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_lng.setFont(font)
        self.label_lng.setObjectName(_fromUtf8("label_lng"))
        self.horizontalLayout_12.addWidget(self.label_lng)
        self.right_pane.addLayout(self.horizontalLayout_12)
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.right_pane.addWidget(self.line_8)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.C = QtGui.QVBoxLayout()
        self.C.setObjectName(_fromUtf8("C"))
        self.slider_a = QtGui.QSlider(self.centralwidget)
        self.slider_a.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_a.sizePolicy().hasHeightForWidth())
        self.slider_a.setSizePolicy(sizePolicy)
        self.slider_a.setMaximum(100)
        self.slider_a.setProperty("value", 0)
        self.slider_a.setOrientation(QtCore.Qt.Vertical)
        self.slider_a.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_a.setObjectName(_fromUtf8("slider_a"))
        self.C.addWidget(self.slider_a)
        self.tool_slider_a = QtGui.QToolButton(self.centralwidget)
        self.tool_slider_a.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/media/icons/padlock_closed_icon&16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/media/icons/padlock_open_icon&16.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tool_slider_a.setIcon(icon2)
        self.tool_slider_a.setCheckable(True)
        self.tool_slider_a.setObjectName(_fromUtf8("tool_slider_a"))
        self.C.addWidget(self.tool_slider_a)
        self.label_24 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.C.addWidget(self.label_24)
        self.horizontalLayout_13.addLayout(self.C)
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.horizontalLayout_13.addWidget(self.line_10)
        self.B = QtGui.QVBoxLayout()
        self.B.setObjectName(_fromUtf8("B"))
        self.slider_b = QtGui.QSlider(self.centralwidget)
        self.slider_b.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_b.sizePolicy().hasHeightForWidth())
        self.slider_b.setSizePolicy(sizePolicy)
        self.slider_b.setMaximum(100)
        self.slider_b.setProperty("value", 0)
        self.slider_b.setOrientation(QtCore.Qt.Vertical)
        self.slider_b.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_b.setObjectName(_fromUtf8("slider_b"))
        self.B.addWidget(self.slider_b)
        self.tool_slider_b = QtGui.QToolButton(self.centralwidget)
        self.tool_slider_b.setIcon(icon2)
        self.tool_slider_b.setCheckable(True)
        self.tool_slider_b.setObjectName(_fromUtf8("tool_slider_b"))
        self.B.addWidget(self.tool_slider_b)
        self.label_25 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.B.addWidget(self.label_25)
        self.horizontalLayout_13.addLayout(self.B)
        self.line_11 = QtGui.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.horizontalLayout_13.addWidget(self.line_11)
        self.A = QtGui.QVBoxLayout()
        self.A.setObjectName(_fromUtf8("A"))
        self.slider_c = QtGui.QSlider(self.centralwidget)
        self.slider_c.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_c.sizePolicy().hasHeightForWidth())
        self.slider_c.setSizePolicy(sizePolicy)
        self.slider_c.setMaximum(100)
        self.slider_c.setProperty("value", 0)
        self.slider_c.setSliderPosition(0)
        self.slider_c.setOrientation(QtCore.Qt.Vertical)
        self.slider_c.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_c.setObjectName(_fromUtf8("slider_c"))
        self.A.addWidget(self.slider_c)
        self.tool_slider_c = QtGui.QToolButton(self.centralwidget)
        self.tool_slider_c.setIcon(icon2)
        self.tool_slider_c.setCheckable(True)
        self.tool_slider_c.setObjectName(_fromUtf8("tool_slider_c"))
        self.A.addWidget(self.tool_slider_c)
        self.label_26 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.A.addWidget(self.label_26)
        self.horizontalLayout_13.addLayout(self.A)
        self.line_12 = QtGui.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.horizontalLayout_13.addWidget(self.line_12)
        self.Bearing = QtGui.QVBoxLayout()
        self.Bearing.setObjectName(_fromUtf8("Bearing"))
        self.dial_bearing = QtGui.QDial(self.centralwidget)
        self.dial_bearing.setEnabled(False)
        self.dial_bearing.setMaximum(360)
        self.dial_bearing.setPageStep(10)
        self.dial_bearing.setProperty("value", 180)
        self.dial_bearing.setWrapping(True)
        self.dial_bearing.setNotchTarget(50.0)
        self.dial_bearing.setNotchesVisible(True)
        self.dial_bearing.setObjectName(_fromUtf8("dial_bearing"))
        self.Bearing.addWidget(self.dial_bearing)
        self.BearingLabel = QtGui.QHBoxLayout()
        self.BearingLabel.setObjectName(_fromUtf8("BearingLabel"))
        self.label_34 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.BearingLabel.addWidget(self.label_34)
        self.label_bearing = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_bearing.setFont(font)
        self.label_bearing.setObjectName(_fromUtf8("label_bearing"))
        self.BearingLabel.addWidget(self.label_bearing)
        self.Bearing.addLayout(self.BearingLabel)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.Bearing.addWidget(self.line_6)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.Bearing.addItem(spacerItem24)
        self.horizontalLayout_13.addLayout(self.Bearing)
        self.right_pane.addLayout(self.horizontalLayout_13)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.right_pane.addWidget(self.line_7)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_29 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_19.addWidget(self.label_29)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem25)
        self.right_pane.addLayout(self.horizontalLayout_19)
        self.stat_peripherals = QtGui.QHBoxLayout()
        self.stat_peripherals.setObjectName(_fromUtf8("stat_peripherals"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.led_GPS = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_GPS.sizePolicy().hasHeightForWidth())
        self.led_GPS.setSizePolicy(sizePolicy)
        self.led_GPS.setState(KLed.Off)
        self.led_GPS.setShape(KLed.Rectangular)
        self.led_GPS.setDarkFactor(400)
        self.led_GPS.setObjectName(_fromUtf8("led_GPS"))
        self.horizontalLayout_15.addWidget(self.led_GPS)
        self.stat_LDAR = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.stat_LDAR.setFont(font)
        self.stat_LDAR.setObjectName(_fromUtf8("stat_LDAR"))
        self.horizontalLayout_15.addWidget(self.stat_LDAR)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem26)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.led_LIDAR = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_LIDAR.sizePolicy().hasHeightForWidth())
        self.led_LIDAR.setSizePolicy(sizePolicy)
        self.led_LIDAR.setState(KLed.Off)
        self.led_LIDAR.setShape(KLed.Rectangular)
        self.led_LIDAR.setDarkFactor(400)
        self.led_LIDAR.setObjectName(_fromUtf8("led_LIDAR"))
        self.horizontalLayout_16.addWidget(self.led_LIDAR)
        self.stat_LDAR_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.stat_LDAR_3.setFont(font)
        self.stat_LDAR_3.setObjectName(_fromUtf8("stat_LDAR_3"))
        self.horizontalLayout_16.addWidget(self.stat_LDAR_3)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem27)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.stat_peripherals.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.led_IMU = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_IMU.sizePolicy().hasHeightForWidth())
        self.led_IMU.setSizePolicy(sizePolicy)
        self.led_IMU.setState(KLed.Off)
        self.led_IMU.setShape(KLed.Rectangular)
        self.led_IMU.setDarkFactor(400)
        self.led_IMU.setObjectName(_fromUtf8("led_IMU"))
        self.horizontalLayout_17.addWidget(self.led_IMU)
        self.stat_LDAR_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.stat_LDAR_2.setFont(font)
        self.stat_LDAR_2.setObjectName(_fromUtf8("stat_LDAR_2"))
        self.horizontalLayout_17.addWidget(self.stat_LDAR_2)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem28)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.led_Raman = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_Raman.sizePolicy().hasHeightForWidth())
        self.led_Raman.setSizePolicy(sizePolicy)
        self.led_Raman.setState(KLed.Off)
        self.led_Raman.setShape(KLed.Rectangular)
        self.led_Raman.setDarkFactor(400)
        self.led_Raman.setObjectName(_fromUtf8("led_Raman"))
        self.horizontalLayout_18.addWidget(self.led_Raman)
        self.stat_LDAR_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        self.stat_LDAR_4.setFont(font)
        self.stat_LDAR_4.setObjectName(_fromUtf8("stat_LDAR_4"))
        self.horizontalLayout_18.addWidget(self.stat_LDAR_4)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem29)
        self.verticalLayout_9.addLayout(self.horizontalLayout_18)
        self.stat_peripherals.addLayout(self.verticalLayout_9)
        self.right_pane.addLayout(self.stat_peripherals)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.right_pane.addWidget(self.line_5)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_14.addWidget(self.label_27)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem30)
        self.right_pane.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.led_rosbag = KLed(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_rosbag.sizePolicy().hasHeightForWidth())
        self.led_rosbag.setSizePolicy(sizePolicy)
        self.led_rosbag.setState(KLed.Off)
        self.led_rosbag.setColor(QtGui.QColor(255, 0, 0))
        self.led_rosbag.setDarkFactor(400)
        self.led_rosbag.setObjectName(_fromUtf8("led_rosbag"))
        self.horizontalLayout_20.addWidget(self.led_rosbag)
        self.label_31 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_20.addWidget(self.label_31)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem31)
        self.tool_rosbag_name = QtGui.QToolButton(self.centralwidget)
        self.tool_rosbag_name.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/media/icons/wrench_icon&16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_rosbag_name.setIcon(icon3)
        self.tool_rosbag_name.setObjectName(_fromUtf8("tool_rosbag_name"))
        self.horizontalLayout_20.addWidget(self.tool_rosbag_name)
        self.tool_rosbag_start = QtGui.QToolButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setBold(True)
        font.setWeight(75)
        self.tool_rosbag_start.setFont(font)
        self.tool_rosbag_start.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/media/icons/playback_rec_icon&16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/media/icons/playback_stop_icon&16.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tool_rosbag_start.setIcon(icon4)
        self.tool_rosbag_start.setCheckable(True)
        self.tool_rosbag_start.setChecked(False)
        self.tool_rosbag_start.setObjectName(_fromUtf8("tool_rosbag_start"))
        self.horizontalLayout_20.addWidget(self.tool_rosbag_start)
        self.right_pane.addLayout(self.horizontalLayout_20)
        self.line_14 = QtGui.QFrame(self.centralwidget)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.right_pane.addWidget(self.line_14)
        spacerItem32 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.right_pane.addItem(spacerItem32)
        self.main_hrz.addLayout(self.right_pane)
        self.horizontalLayout_3.addLayout(self.main_hrz)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stack_mission.setCurrentIndex(2)
        QtCore.QObject.connect(self.tool_rosbag_start, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.led_rosbag.toggle)
        QtCore.QObject.connect(self.combo_mission, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stack_mission.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_2.setText(_translate("MainWindow", "Radio Status", None))
        self.label.setText(_translate("MainWindow", "#0:  900 MHz", None))
        self.label_37.setText(_translate("MainWindow", "Plugged", None))
        self.label_32.setText(_translate("MainWindow", "Paired", None))
        self.progress_radio0.setFormat(_translate("MainWindow", "%v dB", None))
        self.label_3.setText(_translate("MainWindow", "#1:  5.8 GHz", None))
        self.label_36.setText(_translate("MainWindow", "Plugged", None))
        self.label_33.setText(_translate("MainWindow", "Paired", None))
        self.progress_radio1.setFormat(_translate("MainWindow", "%v dB", None))
        self.label_4.setText(_translate("MainWindow", "Camera Status", None))
        self.label_5.setText(_translate("MainWindow", "#0: VR", None))
        self.combo_cam0.setItemText(0, _translate("MainWindow", "5.8", None))
        self.combo_cam0.setItemText(1, _translate("MainWindow", "900", None))
        self.tool_cam0_show.setText(_translate("MainWindow", "0", None))
        self.tool_cam0_start.setText(_translate("MainWindow", "0", None))
        self.label_6.setText(_translate("MainWindow", "#1: Gimbal", None))
        self.combo_cam1.setItemText(0, _translate("MainWindow", "5.8", None))
        self.combo_cam1.setItemText(1, _translate("MainWindow", "900", None))
        self.tool_cam1_show.setText(_translate("MainWindow", "1", None))
        self.tool_cam1_start.setText(_translate("MainWindow", "1", None))
        self.label_7.setText(_translate("MainWindow", "#2: Web1", None))
        self.combo_cam2.setItemText(0, _translate("MainWindow", "5.8", None))
        self.combo_cam2.setItemText(1, _translate("MainWindow", "900", None))
        self.tool_cam2_show.setText(_translate("MainWindow", "2", None))
        self.tool_cam2_start.setText(_translate("MainWindow", "2", None))
        self.label_8.setText(_translate("MainWindow", "#3: Web2", None))
        self.combo_cam3.setItemText(0, _translate("MainWindow", "5.8", None))
        self.combo_cam3.setItemText(1, _translate("MainWindow", "900", None))
        self.tool_cam3_show.setText(_translate("MainWindow", "3", None))
        self.tool_cam3_start.setText(_translate("MainWindow", "3", None))
        self.label_20.setText(_translate("MainWindow", "#4: Web3", None))
        self.combo_cam4.setItemText(0, _translate("MainWindow", "5.8", None))
        self.combo_cam4.setItemText(1, _translate("MainWindow", "900", None))
        self.tool_cam4_show.setText(_translate("MainWindow", "4", None))
        self.tool_cam4_start.setText(_translate("MainWindow", "4", None))
        self.label_14.setText(_translate("MainWindow", "User Input Status", None))
        self.label_16.setText(_translate("MainWindow", "Xbox ", None))
        self.label_19.setText(_translate("MainWindow", "Haptic", None))
        self.label_28.setText(_translate("MainWindow", "Mission Pane", None))
        self.label_21.setText(_translate("MainWindow", "Vehicle: ", None))
        self.label_vehicle.setText(_translate("MainWindow", "Unselected", None))
        self.label_12.setText(_translate("MainWindow", "Setup", None))
        self.button_sandstorm.setText(_translate("MainWindow", "Sandstorm", None))
        self.button_rover.setText(_translate("MainWindow", "2019 Rover", None))
        self.button_simulator.setText(_translate("MainWindow", "Simulator", None))
        self.label_122.setText(_translate("MainWindow", "Extreme Retrieval and Delivery", None))
        self.label_129.setText(_translate("MainWindow", "Autonomous", None))
        self.label_39.setText(_translate("MainWindow", "State: ", None))
        self.label_auto_state.setText(_translate("MainWindow", "Ready", None))
        self.label_35.setText(_translate("MainWindow", "Please enter your destination:", None))
        self.label_22.setText(_translate("MainWindow", "Latitude:", None))
        self.label_23.setText(_translate("MainWindow", "Longitude:", None))
        self.pushButton.setText(_translate("MainWindow", "ENGAGE", None))
        self.label_124.setText(_translate("MainWindow", "Debug", None))
        self.label_9.setText(_translate("MainWindow", "Mode Select", None))
        self.label_38.setText(_translate("MainWindow", "Mission:", None))
        self.combo_mission.setItemText(0, _translate("MainWindow", "Setup", None))
        self.combo_mission.setItemText(1, _translate("MainWindow", "Extreme Retrieval", None))
        self.combo_mission.setItemText(2, _translate("MainWindow", "Autonomous", None))
        self.combo_mission.setItemText(3, _translate("MainWindow", "Debug", None))
        self.button_standby.setText(_translate("MainWindow", "Standby", None))
        self.button_drive.setText(_translate("MainWindow", "Drive", None))
        self.button_arm.setText(_translate("MainWindow", "Arm", None))
        self.button_drill.setText(_translate("MainWindow", "Drill", None))
        self.button_auto.setText(_translate("MainWindow", "Auto", None))
        self.label_10.setText(_translate("MainWindow", "Rover Status", None))
        self.label_11.setText(_translate("MainWindow", "Battery: ", None))
        self.label_voltage.setText(_translate("MainWindow", "0.00 V", None))
        self.progress_voltage.setFormat(_translate("MainWindow", "%v V", None))
        self.label_13.setText(_translate("MainWindow", "Speed:", None))
        self.label_speed.setText(_translate("MainWindow", "0.00 m/s", None))
        self.label_15.setText(_translate("MainWindow", "Relays Active", None))
        self.label_17.setText(_translate("MainWindow", "Latitude:", None))
        self.label_lat.setText(_translate("MainWindow", "0.00000", None))
        self.label_18.setText(_translate("MainWindow", "Longitude:", None))
        self.label_lng.setText(_translate("MainWindow", "0.00000", None))
        self.tool_slider_a.setText(_translate("MainWindow", "...", None))
        self.label_24.setText(_translate("MainWindow", "Max Speed", None))
        self.tool_slider_b.setText(_translate("MainWindow", "...", None))
        self.label_25.setText(_translate("MainWindow", "Turn Rate", None))
        self.tool_slider_c.setText(_translate("MainWindow", "...", None))
        self.label_26.setText(_translate("MainWindow", "Sensitivity", None))
        self.label_34.setText(_translate("MainWindow", "Bearing:", None))
        self.label_bearing.setText(_translate("MainWindow", "0", None))
        self.label_29.setText(_translate("MainWindow", "Peripheral Status", None))
        self.stat_LDAR.setText(_translate("MainWindow", "GPS", None))
        self.stat_LDAR_3.setText(_translate("MainWindow", "LIDAR", None))
        self.stat_LDAR_2.setText(_translate("MainWindow", "IMU", None))
        self.stat_LDAR_4.setText(_translate("MainWindow", "Raman", None))
        self.label_27.setText(_translate("MainWindow", "Utilities", None))
        self.label_31.setText(_translate("MainWindow", "Rosbag Record", None))

from PyKDE4.kdeui import KLed
import res_rc
